### PR TITLE
provide the capability to connect to a different server when using pu…

### PR DESCRIPTION
**Pull request by lmayorga1980**
…ppet agent -t

### CODE REVIEW

**Comment by lmayorga1980** [comment]
@tphoney could you please take a look at this PR? :pray:

**Comment by DavidS** [comment]
Louis, I'm not quite understanding the use-case you are targeting.

* Wouldn't the manifest be injected into the wrong puppetserver, when you pass in a server like this?
* Do you switch servers often within your testsuite?
  * If yes, what benefits does that bring you?
  * If no, shouldn't the server be configured at the same time/level as the test mode (that is, using an environment variable), so that you don't need to spray that all over your testcode?



Other notes:
* when you change `execute_manifest_on`, you also change `execute_manifest`, please note that in the README
* test suites should work unmodified across modes. How should a `local` or `apply` mode handle a specified `server` option? Ignore it, or connect to it, instead of running a local apply?

**Comment by lmayorga1980** [comment]
* I have an scenario where i want to execute the same manifests across 2 pe masters to see the behavior on some server components. I could easily have another nodeset for this but it was just very convenient to execute it this way.
* Yes, often puppet upgrades force us to re-test some of the modules that have lots of dependencies or use special server features and would like to reuse a different running pe-master in the same suite.
* The **server** option just give some flexibility on the master i want to execute a specific suite(specific scenario) and could passed as an __extra__ option. Not a mandatory one.

**Comment by DavidS** [comment]
I'm unconvinced of the general applicability of your use-case. That said, since your change is an optional addition I'm willing to admit it, if it is crafted well. At least:

- [ ] https://github.com/puppetlabs/beaker-testmode_switcher/pull/21/files#diff-976ae1bf4dae7e8e4b019833b4741b1bR84 injects the `manifest` into the `master` node. This entire section needs to change so that `opts[:server]` is a beaker node (defaulting to `master`), and the manifest is injected into the correct node.
- [ ] The README needs to document the change across all functions affected by it (at least `execute_manifest`)
- [ ] The BeakerApplyRunner and the LocalRunner both need to fail when a server is specified.

**Comment by lmayorga1980** [comment]
@DavidS Can you describe a little more the first change that you requested?

**Comment by DavidS** [comment]
when you pass `server` to the `execute_manifest*` functions, in `agent` mode, the manifest needs to be uploaded to the correct master. The code in this PR would upload it to the default master, which would then lead to unexpected failures.

**Comment by lmayorga1980** [comment]
Are you saying that this line https://github.com/puppetlabs/beaker-testmode_switcher/blob/master/lib/beaker/testmode_switcher/beaker_runners.rb#L93-L97 is the one that will execute my extra option on the default master? It makes sense to only execute this command only on the agents. I kind of lost you when you said the correct master. I only use one master node but you are saying that there could be multiple masters and agents could target a specific master?

**Comment by DavidS** [comment]
nope, https://github.com/puppetlabs/beaker-testmode_switcher/blob/master/lib/beaker/testmode_switcher/beaker_runners.rb#L81-L84 will upload the manifest to be executed to the master, and inject it into the `site.pp` there. If you want the agent to connect to a different server, you also need to upload the manifest to that server, otherwise the agent will not execute what you are expecting.

**Pull request closed without merging**
